{{- if .Values.microServices.vault -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    service: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vault
  template:
    metadata:
      labels:
        service: vault
    spec:
      containers:
        - name: myapp
          image: hashicorp/vault:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: {{ .Values.vault.TOKEN | quote }}
            - name: VAULT_ADDR
              value: "http://localhost:8200"
{{- end -}}