{{- if .Values.microServices.myapp -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-demo.fullname" . }}-myapp
  labels:
    service: myapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service: myapp
{{- end -}}
